### ISSUE TITLE
ESXi root partition

### ISSUE THREAD

**Issue by mane** [jensdepuydt/zabbix-vmwareesx#2]
Hi,

This isn't really an issue but a request to see if it's possible to implement a check for the root partition of ESXi.

For the root partition I mean the partition where ESXi is installed and runs.

Thank you.
## 

mane

**Comment by jensdepuydt** [comment]
As far as I know, the root filesystem of an ESX-hosts in a ramdisk.
You could monitor the ramdisk but I can't really seem to get that kind of information via SNMP.

FYI, you can get the size and use of the ramdisks via SSH with command "vdf -h"

**Comment by mane** [comment]
Thanks @jensdepuydt, really appreciated.

## 

mane
